<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByName($name)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM AppBundle:Book p WHERE p.name = '{$name}'"
            )->getResult();
    }

    public function findAllCustom($currentPage, $limit)
    {
         $query = $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM AppBundle:Book p"
            );

        $paginator = $this->paginate($query, (int) $currentPage, $limit);

        return $paginator;
    }

    public function findAllNamesAndPrices()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p.name, p.price FROM AppBundle:Book p"
            )->getResult();
    }

    public function paginate($dql, $page, $limit)
    {
        $paginator = new Paginator($dql);
        $paginator->setUseOutputWalkers(false);

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1)) // Offset
            ->setMaxResults($limit); // Limit

        return $paginator;
    }
}
