<?php
namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllNamesAndPrices()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p.name, p.price FROM AppBundle:Product p"
            )->getResult();
    }
}
