version: '2'
services:
  web:
    container_name: web
    image: nginx:1.15.3-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html/web:ro
#    environment:
#      - NGINX_HOST=foobar.com
#      - NGINX_PORT=80
    depends_on:
      - php
  php:
#    image: php:7.2.10-fpm-alpine3.8
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=bookstore
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass
    depends_on:
      - db
  db:
    image: percona:5.7.23-stretch
    container_name: db
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=SecuredPass
      - MYSQL_DATABASE=bookstore
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass